### PR TITLE
fix: merge side effects

### PR DESCRIPTION
**Pull request by cyrusae**
Recovery from issues with overlapping merges.

1. Fixed Broken Tests & Syntax Errors in  data.rs :
      • Cleaned up syntax errors and unclosed delimiters inside the unit tests module of data.rs.
      • Re-structured the bad merge hunks into distinct, clean unit tests:  test_profile_save_and_load_roundtrip  and test_registry_history_progress_roundtrip .
  2. Added Missing Dependency in  guild-core :
      • Moved  serde_json = { workspace = true }  from  [dev-dependencies]  to  [dependencies]  in Cargo.toml, resolving a compilation error in  crosslink.rs .
  3. Resolved Race Conditions in Environment Variables during Tests:
      • Replaced the local  ENV_LOCK  with the global  crate::TEST_ENV_LOCK  in config.rs for all tests modifying/mocking the  HOME environment variable. This ensures tests running concurrently do not step on each other's environment variables.
      • Removed the unused  std::sync::Mutex  import in  config.rs .
  4. Formatting & Lints:
      • Ran  cargo fmt  to align all code blocks.
      • Confirmed that  cargo clippy --all-targets  and  cargo fmt --check  run cleanly with zero errors/warnings, and all 37 unit tests pass.

### CODE REVIEW

**Comment by cyrusae** [comment]
This is what I get for manual review of merge diffs, sorry about that.
